version: "3"
services:
    redis:
        image: 'redis:3.2.7'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    jobhuntsql:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=jobhunt
            - POSTGRES_PASSWORD=jobhunt
            - POSTGRES_DB=jobhunt
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./jobhuntpgdata:/var/lib/postgresql/data/pgdata

#    notebook:
#        image: jupyter/datascience-notebook
#        restart: always
#        volumes:
#            - ./notebook:/home/jovyan
#        ports:
#            - 8888:8888
#        command: start-notebook.sh --NotebookApp.token=''

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        image: jobhunt/airflow:1.10.10
        restart: always
        depends_on:
            - postgres
            - redis
#            - notebook
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
#            - ./data:/usr/local/airflow/data
            - ./plugins:/usr/local/airflow/plugins
#            - ./notebook:/usr/local/airflow/notebook
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: jobhunt/airflow:1.10.10
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: jobhunt/airflow:1.10.10
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
#            - ./data:/usr/local/airflow/data
            - ./plugins:/usr/local/airflow/plugins
#            - ./notebook:/usr/local/airflow/notebook
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: jobhunt/airflow:1.10.10
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
#            - ./data:/usr/local/airflow/data
            - ./plugins:/usr/local/airflow/plugins
#            - ./notebook:/usr/local/airflow/notebook
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker
